
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sogikjwosozoclvwhnll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvZ2lrandvc296b2NsdndobmxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MTA2NDksImV4cCI6MjA1OTM4NjY0OX0.0qgqwWOtvg1n7g9DPjjco19UNmDsDFR_tqjztIfL3Jc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
